"""blueandme-protocol-map -- generate the protocol map from the profiles.

Deliverable 2 of the brief is a table of ``CAN ID | Direction | Function | Data
format | Source | Confidence``. Generating it from the profile modules rather
than maintaining it by hand means the document cannot drift away from the code,
and cannot quietly claim more confidence than the code enforces.
"""

from __future__ import annotations

import argparse
import sys

from ..protocol.confidence import Confidence
from ..protocol.registry import PROFILES, REFERENCE_ONLY, get

COLUMNS = ("CAN ID", "Dir", "Function", "Data format", "Source", "Confidence")


def rows(profile) -> list[tuple[str, ...]]:
    out = []
    for spec in sorted(profile, key=lambda s: (not s.extended, s.can_id)):
        fmt = []
        if spec.dlc is not None:
            fmt.append(f"{spec.dlc} bytes")
        if spec.period_ms:
            fmt.append(f"{1000 / spec.period_ms:g} Hz")
        if spec.description:
            fmt.append(spec.description)
        out.append((
            spec.hex_id,
            spec.direction.value.upper(),
            spec.name,
            "; ".join(fmt) or "-",
            spec.source,
            spec.confidence.name,
        ))
    return out


def markdown(profile) -> str:
    body = rows(profile)
    width = profile.describe_id_width()
    if profile.id_width_confidence < Confidence.CONFIRMED_940:
        width = f"**{width}**"
    lines = [
        f"## {profile.vehicle}",
        "",
        f"- profile key: `{profile.key}`",
        f"- bitrate: {profile.bitrate} bit/s",
        f"- identifier width: {width}",
        f"- frames known: {len(body)}",
    ]
    if profile.key in REFERENCE_ONLY:
        lines.append("- **REFERENCE ONLY — this profile may never be transmitted.**")
    if profile.notes:
        lines += ["", f"> {profile.notes}"]
    lines += [""]
    if not body:
        lines += [
            "_No frames known yet. This profile is populated only from captures "
            "taken from the vehicle itself; see `README.md`._",
            "",
        ]
        return "\n".join(lines)
    lines.append("| " + " | ".join(COLUMNS) + " |")
    lines.append("|" + "|".join("---" for _ in COLUMNS) + "|")
    for row in body:
        lines.append("| " + " | ".join(c.replace("|", r"\|") for c in row) + " |")
    lines.append("")
    if profile.buttons:
        lines += [
            "### Steering-wheel button masks", "",
            "| Button | Mask |", "|---|---|",
            *[f"| {b.name} | `0x{b.mask:0{b.width * 2}X}` |" for b in profile.buttons],
            "",
        ]
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="blueandme-protocol-map",
        description="Emit the protocol map as Markdown, generated from the profiles.",
    )
    p.add_argument(
        "--profile", action="append", default=[],
        help=f"profiles to emit (default: all). Available: {', '.join(sorted(PROFILES))}",
    )
    return p


def main(argv: "list[str] | None" = None) -> int:
    args = build_parser().parse_args(argv)
    keys = args.profile or ["giulietta940", "doblo263", "alfa939"]
    try:
        profiles = [get(k) for k in keys]
    except KeyError as exc:
        print(exc, file=sys.stderr)
        return 2
    print("# Protocol map\n")
    print(
        "Generated by `blueandme-protocol-map`. Every row's confidence is the "
        "value the transmit gate enforces at runtime.\n"
    )
    for profile in profiles:
        print(markdown(profile))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
